name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true
      - name: Vet & Test
        run: |
          go vet ./...
          go test ./... -count=1
      - name: Build
        run: go build ./cmd/codectx
